# Generated by Django 5.0.3 on 2024-03-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='form1s', to='chamber.director'),
        ),
    ]
