# Generated by Django 5.0.3 on 2024-03-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='chamber_day_celebrations',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='journal_subscription',
            field=models.BooleanField(),
        ),
    ]
