# Generated by Django 5.0.3 on 2024-03-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0002_form1_directors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form1',
            name='association_name_position',
        ),
        migrations.AddField(
            model_name='form1',
            name='association_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Association Name'),
        ),
        migrations.AddField(
            model_name='form1',
            name='association_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Association Position'),
        ),
    ]
