# Generated by Django 5.0.3 on 2024-03-17 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0002_alter_paymenttransaction_chamber_day_celebrations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventimage', models.FileField(null=True, upload_to='eventsimage/', verbose_name='')),
                ('NameofEvent', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=1000)),
                ('DateofEvent', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
