# Generated by Django 5.0.3 on 2024-03-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0003_remove_form1_association_name_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='sn_no',
        ),
    ]
