# Generated by Django 5.0.3 on 2024-03-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0004_remove_director_sn_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='cdlan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cdphone',
            field=models.IntegerField(),
        ),
    ]
