# Generated by Django 5.0.3 on 2024-03-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0005_alter_form1_cdlan_alter_form1_cdphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='pan',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
