# Generated by Django 5.0.3 on 2024-03-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0009_alter_contact_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Phone', models.BigIntegerField(null=True)),
                ('Xray', models.FileField(null=True, upload_to='Xray/', verbose_name='Xray Image')),
                ('Result_XRay', models.FileField(null=True, upload_to='Result/', verbose_name='Result Image')),
                ('Report_1', models.TextField(null=True)),
                ('Report_2', models.TextField(null=True)),
                ('Report_3', models.TextField(null=True)),
                ('Report_4', models.TextField(null=True)),
                ('Report_5', models.TextField(null=True)),
                ('result', models.CharField(blank=True, choices=[('Fractured', 'Fractured'), ('Not Fractured', 'Not Fractured')], max_length=30, null=True)),
                ('Disease', models.CharField(blank=True, choices=[('Elbow Positive', 'Elbow Positive'), ('Fingers Positive', 'Fingers Positive'), ('Forearm Fracture', 'Forearm Fracture'), ('Humerus Fracture', 'Humerus Fracture'), ('Shoulder Fracture', 'Shoulder Fracture'), ('Wrist Positive', 'Wrist Positive')], max_length=50, null=True)),
            ],
        ),
    ]
