# Generated by Django 5.0.3 on 2024-03-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0010_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
