# Generated by Django 5.0.3 on 2024-05-02 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0011_delete_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='form_status',
            field=models.CharField(choices=[('pending', 'pending'), ('waiting for payment', 'waiting for payment'), ('payment done (approved)', 'payment done (approved)'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='form1',
            name='ror',
            field=models.TextField(blank=True, help_text='Reason of Rejection', null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cdemail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='form1',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
