# Generated by Django 5.0.3 on 2024-05-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0012_form1_form_status_form1_ror_alter_form1_cdemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='chamber_day_celebrations',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='journal_subscription',
        ),
    ]
