# Generated by Django 5.0.3 on 2024-05-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0013_remove_paymenttransaction_chamber_day_celebrations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='expiry_date',
            field=models.CharField(max_length=100),
        ),
    ]
