# Generated by Django 5.0.3 on 2024-05-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0014_alter_paymenttransaction_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='cvv',
            field=models.CharField(max_length=40),
        ),
    ]
