# Generated by Django 5.0.3 on 2024-05-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0015_alter_paymenttransaction_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='cdemail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
