# Generated by Django 5.0.3 on 2024-05-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0016_alter_form1_cdemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='aadhar',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cdphone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='pancardno',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
