# Generated by Django 5.0.3 on 2024-05-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0017_alter_form1_aadhar_alter_form1_cdphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='form_status',
            field=models.CharField(choices=[('pending', 'pending'), ('Approved by AO', 'Approved by AO'), ('Approved by CEO', 'Approved by CEO'), ('Approved by Membership Committee', 'Approved by Membership Committee'), ('Approved by OB', 'Approved by OB'), ('Approved as a Member', 'Approved as a Member'), ('waiting for payment', 'waiting for payment'), ('payment done (approved as Member)', 'payment done (approved as Member)'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
