# Generated by Django 5.0.3 on 2024-05-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0018_alter_form1_form_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='membership_type',
            field=models.CharField(choices=[('general', 'General'), ('professional', 'Professional'), ('associations', 'Associations'), ('life', 'Life Membership')], max_length=20),
        ),
    ]
