# Generated by Django 5.0.3 on 2024-05-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0019_alter_paymenttransaction_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='Businessactivity',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='CompanyFirmRegNo',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='GSTNo',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Nameofapplicant',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='SocietyAssociationRegNo',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='aadhar',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='acoffice',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='acwork',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='annual_turnover_year1',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='annual_turnover_year2',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='annual_turnover_year3',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='association_position',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Association Position'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cdemail',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cdlan',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cdphone',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cdweb',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='classindustry',
            field=models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small'), ('Micro', 'Micro')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cmboth',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cmdomestic',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cmglobal_market',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cmpercentage_of_exports',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cmpercentage_of_imports',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='collaborator_name_foreign_collaboration',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='country_name_foreign_collaboration',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='direct_office_employees',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='epf',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='esic',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='indirect_contractual_employees',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='indmain_category',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='indsub_category',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='outsourced_employees',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='paaadhaar',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='padesignation',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='pamail_id',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='paname',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='papan',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='paphone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='reason_for_joining_chamber',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='regoffadd',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='ror',
            field=models.TextField(blank=True, default=None, help_text='Reason of Rejection', null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='works_employees',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
