# Generated by Django 5.0.3 on 2024-05-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0020_alter_form1_businessactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='cdlan',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='cdphone',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
