# Generated by Django 5.0.3 on 2024-05-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0025_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_content',
        ),
    ]
