# Generated by Django 5.0.3 on 2024-05-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0026_remove_certificate_certificate_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='user',
        ),
        migrations.AddField(
            model_name='certificate',
            name='Name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
